name: terra-flow-action-workflow

on:
  workflow_call:
    inputs:
      terraform_action:
        description: Terraform action to execute i.e. plan, apply, destroy
        required: true
        type: string
      terraform_version:
        description: Terraform version
        default: 1.9
        type: string
      terraform_workspace:
        description: Terraform workspace name
        required: true
        type: string
      terraform_directory:
        description: Terraform root directory
        required: true
        type: string
      environment:
        description: Environment name test, dev, prod
        required: true
        type: string
      aws_account_id:
        description: AWS account id
        required: true
        type: string
      aws_region:
        description: AWS region name
        default: us-east-1
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terra-flow-run:
    name: terra-flow-${{ inputs.terraform_action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Checkout terra-flow
        uses: actions/checkout@v4
        with:
          repository: curtrube/terra-flow
          ref: main
          path: terra-flow
      
      - name: list directory
        run: ls -la

      - name: AWS assume role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::992382678496:role/GitHubActionsAdminRole

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Print terra flow inputs
        run: | 
          echo "Terraform Action: ${{ inputs.terraform_action }}"
          echo "Terraform Workspace: ${{ inputs.terraform_workspace }}"
          echo "Terraform Directory: ${{ inputs.terraform_directory }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "AWS Account Id: ${{ inputs.aws_account_id }}"
          echo "AWS Region: ${{ inputs.aws_region }}"

      - name: Terra Flow ${{ inputs.terraform_action }}
        run: |
          chmod +x terra-flow/terra-flow
          terra-flow/terra-flow \
            -a ${{ inputs.terraform_action }} \
            -w ${{ inputs.terraform_workspace }} \
            -d ${{ inputs.terraform_directory }} \
            -e ${{ inputs.environment }} \
            -i ${{ inputs.aws_account_id }} \
            -r ${{ inputs.aws_region }}
        shell: bash