name: terra-flow-action-workflow

on:
  workflow_call:
    inputs:
      terraform_action:
        description: Terraform action to execute i.e. plan, apply, destroy
        required: true
        type: string
      terraform_version:
        description: Terraform version
        default: 1.9
        type: string
      terraform_workspace:
        description: Terraform workspace name
        required: true
        type: string
      terraform_directory:
        description: Terraform root directory
        required: true
        type: string
      environment:
        description: Environment name test, dev, prod
        required: true
        type: string
      aws_account_prefix:
        description: AWS account prefix
        required: true
        type: string
      aws_region:
        description: AWS region name
        default: us-east-1
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  terra-flow-run:
    name: terra-flow-${{ inputs.terraform_action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Checkout terra-flow
        uses: actions/checkout@v4
        with:
          repository: curtrube/terra-flow
          ref: main
          path: terra-flow

      - name: AWS assume role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::992382678496:role/GitHubActionsAdminRole
      
      - name: Get AWS account id
        id: get-account-id
        run: |
          echo "aws_account_id=$(aws ssm get-parameter --name "/accounts/${{ inputs.aws_account_prefix }}/${{ inputs.environment }}" --with-decryption --query "Parameter.Value" --output text)" >> $GITHUB_OUTPUT

      # then assume access into the account the desired account
      - name: AWS assume role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ steps.get-account-id.outputs.aws_account_id }}:role/GitHubActionsAdminRole

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terra Flow ${{ inputs.terraform_action }}
        run: |
          chmod +x terra-flow/terra-flow
          terra-flow/terra-flow \
            -a ${{ inputs.terraform_action }} \
            -w ${{ inputs.terraform_workspace }} \
            -d ${{ inputs.terraform_directory }} \
            -e ${{ inputs.environment }} \
            -i ${{ steps.get-account-id.outputs.aws_account_id }} \
            -r ${{ inputs.aws_region }}
        shell: bash